source 'https://rubygems.org'
ruby '2.3.0'
gem 'cuba'
gem 'cuba-contrib'
gem 'mote'
gem 'cutest'
gem 'rack-test'
gem 'rack-protection'
gem 'puma', '~> 2.15.3'
gem 'rest-client'
gem 'ohm'
gem 'ohm-contrib'
